-- ADD IMAGE DESCRIPTION COLUMN TO NOTES TABLE
ALTER TABLE notes ADD COLUMN IF NOT EXISTS image_description TEXT;

-- ADD COMMENT TO EXPLAIN THE COLUMN
COMMENT ON COLUMN notes.image_description IS 'DESCRIPTION OF THE IMAGE FOR CONTEXT (REQUIRED WHEN IMAGE_URL IS PROVIDED)';

-- ADD CHECK CONSTRAINT TO ENSURE IMAGE DESCRIPTION IS PROVIDED WHEN IMAGE EXISTS
ALTER TABLE notes ADD CONSTRAINT check_image_description 
  CHECK (
    (image_url IS NULL AND image_description IS NULL) OR 
    (image_url IS NOT NULL AND image_description IS NOT NULL AND LENGTH(TRIM(image_description)) > 0)
  );
