-- ADD IMAGE_URL COLUMN TO NOTES TABLE
ALTER TABLE notes ADD COLUMN IF NOT EXISTS image_url TEXT;

-- ADD COMMENT TO EXPLAIN THE COLUMN
COMMENT ON COLUMN notes.image_url IS 'SUPABASE STORAGE URL FOR NOTE IMAGE';
