-- ALLOW NULL VALUES IN RATING COLUMN FOR FEEDBACK-ONLY UPDATES
ALTER TABLE message_ratings ALTER COLUMN rating DROP NOT NULL;

-- ADD COMMENT TO EXPLAIN THE CHANGE
COMMENT ON COLUMN message_ratings.rating IS 'RATING CAN BE NULL FOR FEEDBACK-ONLY UPDATES, 1 FOR THUMBS UP, -1 FOR THUMBS DOWN';
