# Supabase Configuration
# IMPORTANT: This should be the SERVICE ROLE key, not the anon key
SUPABASE_KEY_OLD = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kbmdza3JreWZhYmNzdGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NTI1NzYsImV4cCI6MjA2NzIyODU3Nn0.kpVXIevGRc-3dqyc3F7qKsD6AVtz4ibxXdptJAWXcZ4"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kbmdza3JlaWpyeWZhYmNzdGNxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTY1MjU3NiwiZXhwIjoyMDY3MjI4NTc2fQ.z-KRQIUA5i6jQnQ6o65L04NcrrfRNlQ5QhHwFYgxBaU"
SUPABASE_URL = "https://mdngskreijryfabcstcq.supabase.co"

# AWS Configuration
AWS_ACCESS_KEY_ID = "AKIAU5WIQGY6HB3EGAXW"
AWS_SECRET_ACCESS_KEY = "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"
AWS_DEFAULT_REGION = "us-east-1"
AWS_REGION = "us-east-1"

# Document Storage
DOC_BUCKET = "doc-store-prod-stryker"

# OpenAI Configuration
OPENAI_API_KEY = "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" 